<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevApp_TFF_Sortilege__WebAPI.ApplicationCore\DevApp_TFF_Sortilege__WebAPI.ApplicationCore.csproj" />
    <ProjectReference Include="..\DevApp_TFF_Sortilege__WebAPI.Domain\DevApp_TFF_Sortilege__WebAPI.Domain.csproj" />
    <ProjectReference Include="..\DevApp_TFF_Sortilege__WebAPI.Infrastructure.Database\DevApp_TFF_Sortilege__WebAPI.Infrastructure.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Hubs\" />
  </ItemGroup>

</Project>
