// <auto-generated />
using System;
using DevApp_TFF_Sortilege__WebAPI.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevApp_TFF_Sortilege__WebAPI.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312075753_Correc HashWord Required")]
    partial class CorrecHashWordRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevApp_TFF_Sortilege__WebAPI.Domain.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(true)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("HashWord")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Hash_Mot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Pseudo");

                    b.HasKey("Id")
                        .HasName("PK_Membres");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_Membres__Email");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UK_Membres__Pseudo");

                    b.ToTable("Membres", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
